env_name: hopper

# training parameters
gamma: 0.995
tau: 0.95
policy_spec:
  htype: tanh
  control_gnn_spec:
    layer_type: graph_conv
    hdims: [64, 64, 64]
    aggr: add
    bias: true
  control_index_mlp:
    hdims: [128, 128]
    rescale_linear: true
  control_log_std: 0
  fix_control_std: false
policy_optimizer: 'Adam'
policy_lr: 5.e-5
policy_momentum: 0.0
policy_weightdecay: 0.0

value_spec:
  htype: tanh
  onehot_design_flag: true
  mlp: [512, 256]
  gnn_spec:
    layer_type: graph_conv
    hdims: [64, 64, 64]
    aggr: add
    bias: true
value_optimizer: 'Adam'
value_lr: 3.e-4
value_momentum: 0.0
value_weightdecay: 0.0

clip_epsilon: 0.2
min_batch_size: 50000
mini_batch_size: 2048
num_optim_epoch: 10
max_epoch_num: 1000
seed: 1


obs_spec:
  attr: ['depth']
  sim: []
  design: true
  clip_qvel: true
  use_projected_params: true
  use_body_ind: true
max_body_depth: 4

  
